### ISSUE TITLE
Reel-piece implementation.

### ISSUE THREAD

**Issue by digitalextremist** [celluloid/ecell#14]
Piece which behaves as `Reel` http/s|ws/s server, solely:

- [x] Provides access to static files on the host in a specific directory ( and its contained directories, recursively )
- [x] Outputs request statistics to logger ( summary of every request: url, time to serve, method, host address )

**Comment by benzrf** [comment]
Er - what's the utility of this, exactly? It seems like it wouldn't even really involve any ECell stuff at all.

**Comment by digitalextremist** [comment]
It is an example of "wrapping" an existing server or library -- this piece is very quick to do, but will be very valuable to existing `Reel` users and those of many similar libraries, because it demonstrates how to wrap their own implementations.

**Comment by benzrf** [comment]
Implemented (unless "http/s|ws/s" means I need to get WebSockets and SSL/TLS working).
