### ISSUE TITLE
Should I migrate the Admin role?

### ISSUE THREAD

**Issue by benzrf** [celluloid/ecell#3]
Right now it's just commented out. Is that because it's broken and I should fix it while migrating, or because it's abandoned and should be left out?

**Comment by digitalextremist** [comment]
It was not made/finished. Do migrate it but as an undeveloped piece.

**Comment by benzrf** [comment]
You mean I should update it without fully fixing it?

**Comment by digitalextremist** [comment]
@benzrf you are talking about the `Admin` role implemented in `Hostmaster` which was never finished, and honestly was barely begun. Migrate the semantics as it currently stands, transposing nomenclature, etc -- but I do not expect it to run yet. I will instead post a follow-up ticket handling its completion.

**Comment by benzrf** [comment]
Alright, will do :)
