### ISSUE TITLE
Leader doesn't reattach to restarted pieces

### ISSUE THREAD

**Issue by benzrf** [celluloid/ecell#6]
If `follower_attach` is called with a piece that the leader thinks it's already attached to, it will refuse to try attaching again unless it can't ping the piece. At the same time, pieces that are noted as unresponsive aren't actually deleted from the list of attached pieces. Together, this means that when a service goes down and comes back up, its leader will think it's still attached, so it will refuse to attach again.

**Comment by benzrf** [comment]
I could probably write a hacky fix for this fairly quickly, but if I want to do it right, I think it might require rethinking the whole process lifecycle. At the same time, there's some similar changes that'd have to go into #5. It feels like a waste to do a bunch of work if it's just going to be replaced again, so if I do end up doing #5, I think I'd want to do it before or at the same time as this. But if #5 ends up being out of scope, I guess I could just do the smaller-scale redesign.

So the question is: Do you think #5 is something I should go forward with, or should I focus on the other stuff?

**Comment by digitalextremist** [comment]
I see the connection between this and #5.

As with other comments where I mentioned the goal of a skeleton as covering all the necessary upcoming items as more of a to-do list, start by laying out a checklist of everything that needs to be done to satisfy this and #5, either in a new meta-issue combining both but spelling out each individual piece involved in the solution -- or by editing the original tickets to be checklists. Then go through the checklist and at the end we will see where you stand with them, and there will be clarity on what the remaining tasks are.

**Comment by benzrf** [comment]
Alright, fixed this. It's probably worth noting that followers currently still don't notice if their leader leaves - but that doesn't appear to have been intended behavior, because there's nothing anywhere that accounts for followers being able to tell if they have a leader, besides the leader instructing them to recognize it.
